### ISSUE TITLE
It uses all my RAM and it crashes

### ISSUE THREAD

**Issue by start-life** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#10]
How can you limit the amount of RAM it loads?

**Comment by lifeisboringsoprogramming** [comment]
how much VRAM do you have?

**Comment by evgebrtwjhr** [comment]
I have 8 gigabytes, but it takes up the normal RAM of my computer, not the video card, I have an RTX 3070 card

**Comment by start-life** [comment]
I have 8 gigabytes, but it takes up the normal RAM of my computer, not the video card, I have an RTX 3070 card

**Comment by lifeisboringsoprogramming** [comment]
I'm looking into the memory issue, thanks
