### ISSUE TITLE
issue with locating safetensors

### ISSUE THREAD

**Issue by highrup** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#12]
i finally got it to load after disabling all my other extensions, however its getting alternate issues locating a file
Loading model stabilityai/stable-diffusion-xl-base-0.9
vae\diffusion_pytorch_model.safetensors not found
Loading model stabilityai/stable-diffusion-xl-refiner-0.9
unet\diffusion_pytorch_model.safetensors not found

or ill get this error in the same spot after a reload
Loading model stabilityai/stable-diffusion-xl-base-0.9
text_encoder_2\model.safetensors not found
Loading model stabilityai/stable-diffusion-xl-refiner-0.9
text_encoder_2\model.safetensors not found

if i download the top files where should i drop them?
same for the later but i think that the second one is from disabling a plugin

**Comment by xueqing0622** [comment]
I put the vae from hugging face to model/vae, but doesn't work for unet put in model/unet, where should I put the unet.
Loading model stabilityai/stable-diffusion-xl-base-0.9
unet\diffusion_pytorch_model.safetensors not found
Loading model stabilityai/stable-diffusion-xl-refiner-0.9
unet\diffusion_pytorch_model.safetensors not found

**Comment by highrup** [comment]
Yeah I saw the vae folder but I figured I'd ask for clarity, I got them both downloaded just need to know the directory its searching in for the unet

**Comment by highrup** [comment]
to add to this i now have all my extensions enabled aside from dreambooth and sdxl has also booted up fine, how no its consistent in showing this as well for those not found files, but it does generate images as well as refine them, im curious about those files tho. enabling dreambooth gives me the same error everyone else has been posting lately

Loading model stabilityai/stable-diffusion-xl-base-0.9
text_encoder\model.safetensors not found
Loading model stabilityai/stable-diffusion-xl-refiner-0.9
unet\diffusion_pytorch_model.safetensors not found

i attached my plugins as well if you have any ideas OP?
![image](https://github.com/lifeisboringsoprogramming/sd-webui-xldemo-txt2img/assets/10265852/76743f80-5b36-4b75-b979-f2db6c2dfa72)

**Comment by lifeisboringsoprogramming** [comment]
On Windows, I have similar errors when starting up, I forgot exactly the message, but I just ignore them and I can still generate the image

Loading model stabilityai/stable-diffusion-xl-base-0.9
text_encoder_2\model.safetensors not found
Loading model stabilityai/stable-diffusion-xl-refiner-0.9
text_encoder_2\model.safetensors not found

**Comment by highrup** [comment]
cool feel free to close this once you figure out the comp issue between dreambooth and this one (same error that was closed recently), they both work fine just not enabled together, hopefully this can help nail it down to whatever is shared between them

issue fixed by updating dreambooth
