### ISSUE TITLE
*** Error adding [prompt_spaces] to filename。    AttributeError: 'list' object has no attribute 'translate'

### ISSUE THREAD

**Issue by swumagic** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#19]
I input the prompt word, and then two errors are displayed like this, but the picture can still be drawn after waiting 8-10 minutes, that is, there is the above error prompt.
I input the prompt word： best quality, masterpiece,1girl,indoors。and then two errors are displayed like this

*** Error adding [prompt_spaces] to filename
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\images.py", line 462, in apply
        replacement = fun(self, *pattern_args)
      File "M:\SD\sdwebui\modules\images.py", line 367, in <lambda>
        'prompt_spaces': lambda self: sanitize_filename_part(self.prompt, replace_spaces=False),
      File "M:\SD\sdwebui\modules\images.py", line 332, in sanitize_filename_part
        text = text.translate({ord(x): '_' for x in invalid_filename_chars})
    AttributeError: 'list' object has no attribute 'translate'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by jasoncow007** [comment]
me too，same issue when generate pic

**Comment by bjornlarssen** [comment]
I sorted this out by putting [seed] in settings as filename template (instead of default blank).

**Comment by lifeisboringsoprogramming** [comment]
thanks for debugging it

**Comment by swumagic** [comment]
> I sorted this out by putting [seed] in settings as filename template (instead of default blank).

[seed]-1？seed how to set filename template？thanks

**Comment by bjornlarssen** [comment]
Settings > Saving images/grids > [wiki] filename pattern > enter "[seed]" and tick "add number to filename while saving."

You will get filenames like 0001 9384948.png with the parameters/prompts/etc. embedded in the file, you can check them using PNG Info. (I right-click the images I want to keep and use "save as" anyway.)

**Comment by swumagic** [comment]
thanks!

**Comment by swumagic** [comment]
> 设置 > 保存图像/网格 > [wiki] 文件名模式 > 输入“[种子]”并勾选“保存时向文件名添加数字”。
> 
> 您将获得类似 0001 9384948.png 的文件名以及参数/提示/等。嵌入在文件中，您可以使用 PNG Info 来检查它们。（我右键单击要保留的图像并使用“另存为”。）
I set SEED, but still have the above error message. Don't you have the above error message here?
