### ISSUE TITLE
Feature request: "Send to refiner"

### ISSUE THREAD

**Issue by bjornlarssen** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#25]
It seems that in order to use the refiner I have to save the image, then drag it to the refiner, and then click refine. When I just generate it and click "refine" I get an error – 'Please set the image for refiner.'

Thanks in advance!

**Comment by lifeisboringsoprogramming** [comment]
yes you need to drag an image to the refiner image box, just like img2img

**Comment by bjornlarssen** [comment]
AHHHH. This either didn't work before or I did it wrong. I can indeed just drag. Sorry!
