### ISSUE TITLE
Tabulation not appear

### ISSUE THREAD

**Issue by ghost** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#40]
Hello,

After several attempts, the installation is "successful" (no error message), but no new tabulation is visible. In the configuration, I also do not see any new configuration options.
I have a similar installation on another (much less powerful) computer where everything went perfectly.

I'm not sure where to look. Thank you for your help.

**Comment by mbaltera-10408** [comment]
Have the same issue. Installed and configure. If I restart the instance, the tab and the setting disappear.

venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0



No module 'xformers'. Proceeding without it.
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: c2a5617c587b812b5a408143ddfb18fc49234edf
[!] xformers NOT installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.35.4 installed.


Launching Web UI with arguments: --listen --port 7861 --gradio-auth-path Users\Users-Port7861.txt --hide-ui-dir-config --theme dark --skip-version-check --skip-python-version-check --skip-install
No module 'xformers'. Proceeding without it.
2023-07-17 11:38:13,344 - ControlNet - INFO - ControlNet v1.1.232
ControlNet preprocessor location: C:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-07-17 11:38:13,407 - ControlNet - INFO - ControlNet v1.1.232
Error loading script: sd_webui_xldemo_txt2img.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 4, in <module>
    from xldemo_txt2img_ui import make_ui
  File "C:\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 7, in <module>
    from xldemo_txt2img import XLDEMO_HUGGINGFACE_ACCESS_TOKEN, XLDEMO_LOAD_REFINER_ON_STARTUP
  File "C:\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 19, in <module>
    from diffusers.schedulers.scheduling_dpmsolver_sde import DPMSolverSDEScheduler as dpmsolver_sde
ModuleNotFoundError: No module named 'diffusers.schedulers.scheduling_dpmsolver_sde'

Loading weights [c0d1994c73] from C:\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV20_v20.safetensors
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Textual inversion embeddings loaded(0):
Model loaded in 2.6s (load weights from disk: 0.2s, create model: 0.5s, apply weights to model: 0.5s, apply half(): 0.4s, move model to device: 0.3s, load textual inversion embeddings: 0.7s).
Applying optimization: Doggettx... done.
CUDA SETUP: Loading binary C:\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://0.0.0.0:7861

To create a public link, set `share=True` in `launch()`.
Startup time: 9.2s (import torch: 1.5s, import gradio: 1.0s, import ldm: 0.4s, other imports: 0.8s, load scripts: 4.5s, create ui: 0.4s, gradio launch: 0.6s).

**Comment by lifeisboringsoprogramming** [comment]
the dreambooth instsalled diffusers version 0.16.1 
it should replaced the required version 0.18.1

you can try to disable the dreambooth
or update the dreambooth diffusers version to 0.18.1

**Comment by Yoke-pixel** [comment]
I get this, can someone help.

Traceback (most recent call last):
  File "C:\webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\webui\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 9, in on_ui_tabs
    return [(make_ui(), "SDXL Demo", "xldemo_txt2img")]
  File "C:\webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 96, in make_ui
    xldemo_txt2img_seed, xldemo_txt2img_reuse_seed = create_seed_inputs(id_part)
  File "C:\webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui_common.py", line 30, in create_seed_inputs
    random_seed = ToolButton(
TypeError: ToolButton.__init__() takes 1 positional argument but 2 were given

**Comment by ghost** [comment]
Sorry i read very late the message.
For me it's perfectly running now. Thanks
