### ISSUE TITLE
CMD Have some BUG prompt。But txt 2img work.Dear author, can you cancel these BUG hints/THNAKS

### ISSUE THREAD

**Issue by swumagic** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#43]
CMD Have some BUG prompt。But txt 2img work.Dear author, can you cancel these BUG hints/THNAKS
Using SDXL 0.9
Loading model stabilityai/stable-diffusion-xl-base-0.9
text_encoder_2\model.safetensors not found
Loading model stabilityai/stable-diffusion-xl-refiner-0.9
text_encoder_2\model.safetensors not found

**Comment by lifeisboringsoprogramming** [comment]
this is not output by me, it's form the diffusers package
